### ISSUE TITLE
errors and tracebacks only provided in a subset of cases

### ISSUE THREAD

**Issue by dkoppstein** [maxplanck-ie/dissectBCL#99]
In some cases, dissect will fail silently, or provide a cryptic email without a traceback on the command line or in a log. If there is an error and we want the pipeline to fail, it should be handled then explicitly re-raised as an Exception. This is not mutually exclusive with #97, as we want the worker thread to explicitly fail for a particular demux instance, touch the corresponding pipeline failed flag, then reraise the exception, and for the main process to continue.

**Comment by dkoppstein** [comment]
using logging.exception("Some message") should allow you to explicitly catch, log, and re-raise the message to get the traceback.

**Comment by WardDeb** [comment]
Lack of traceback was due to #61 , which was fixed in #110
